// <auto-generated />
using System;
using Booking_Backend.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Booking_Backend.Data.Migrations
{
    [DbContext(typeof(BookingContext))]
    [Migration("20240315060752_ChangeServicetoServiceHotel")]
    partial class ChangeServicetoServiceHotel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Booking_Backend.Data.Entities.AppConfig", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("AppConfigs");
                });

            modelBuilder.Entity("Booking_Backend.Data.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("265e11da-bc22-4fe7-b286-493d6a09d46f"),
                            ConcurrencyStamp = "2a1c35c2-82ee-41cd-93ab-780e5a738093",
                            Description = "Quản trị viên - quản lí tài khoản và kiểm duyệt người dùng",
                            Name = "Administrators",
                            NormalizedName = "ADMINISTRATORS"
                        },
                        new
                        {
                            Id = new Guid("f0404419-a456-4cd6-a8bc-e19c246904c5"),
                            ConcurrencyStamp = "9469b7d0-76dd-486a-9e7d-e6327bed4c45",
                            Description = "Chủ sở hữu - quản lí tài sản cá nhân, đăng bài và quản lí khách hàng",
                            Name = "Owner",
                            NormalizedName = "OWNER"
                        },
                        new
                        {
                            Id = new Guid("1f10d63e-c240-4be5-a95b-b868c41501dd"),
                            ConcurrencyStamp = "e0d0be7a-f6a6-4f34-9b53-43bd26aefbd5",
                            Description = "Khách hàng đăng nhập - quản lí tài khoản cá nhân và thuê phòng",
                            Name = "Client",
                            NormalizedName = "CLIENT"
                        },
                        new
                        {
                            Id = new Guid("ad9c3bfc-fd01-4696-b8c8-0ce10e6a3632"),
                            ConcurrencyStamp = "7c988bbc-16b4-4540-ab5e-6558af1ac373",
                            Description = "Người dùng duyệt web - xem thông tin khách sạn",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Booking_Backend.Data.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 3, 15, 6, 7, 51, 244, DateTimeKind.Utc).AddTicks(2016));

                    b.Property<int>("Dashboard")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nation")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b5e9ebbd-fd85-4ad0-b820-0aa8105ebdd2"),
                            AccessFailedCount = 0,
                            Address = "An Phú, An Hòa, Châu Thành, An Giang",
                            Birthday = new DateTime(2002, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "9d701eb5-3bed-4813-a990-228f97474537",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dashboard = 352642218,
                            DisplayName = "Hà Vĩ Khang",
                            Email = "hvikhang_21th@student.agu.edu.vn",
                            EmailConfirmed = true,
                            FirstName = "Vĩ",
                            Gender = "Nam",
                            LastName = "Khang",
                            LockoutEnabled = false,
                            Nation = "Việt Nam",
                            NormalizedEmail = "hvikhang_21th@student.agu.edu.vn",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAELHF2XfOl2qlfUg2KJGCw4tr7Xx+ByjOdpMbBZ0TfyxA12Er4Ra+NeUj9v2u1HFHwA==",
                            PhoneNumber = "0339141910",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            Status = 0,
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("31ff741e-5a2a-4afd-8448-7dc59c03a5b6"),
                            AccessFailedCount = 0,
                            Address = "Châu Phong, Tân Châu, An Giang",
                            Birthday = new DateTime(2002, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "273505bf-6867-4727-82b9-d85d9b489f13",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dashboard = 354261197,
                            DisplayName = "Hà Thị Mỹ Tiên",
                            Email = "htmtien_21av@student.agu.edu.vn",
                            EmailConfirmed = true,
                            FirstName = "Mỹ",
                            Gender = "Nu",
                            LastName = "Tiên",
                            LockoutEnabled = false,
                            Nation = "Việt Nam",
                            NormalizedEmail = "htmtien_21av@student.agu.edu.vn",
                            NormalizedUserName = "MYTIEN",
                            PasswordHash = "AQAAAAEAACcQAAAAEFQaK5tHMzr65pGMnAvzHpjQlcJOVyee7mTVja5lGdVbd3w+6CUlbrdnd1UIZROKVQ==",
                            PhoneNumber = "0357642951",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            Status = 0,
                            TwoFactorEnabled = false,
                            UserName = "MyTien"
                        });
                });

            modelBuilder.Entity("Booking_Backend.Data.Entities.Bed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Beds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Một giường 1m x 1.2m",
                            Language = "vi-VN",
                            Name = "Giường đơn"
                        },
                        new
                        {
                            Id = 2,
                            Description = "One bed 1m x 1.2m",
                            Language = "en-US",
                            Name = "Single Bed"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Một giường nhỏ 1.5m x 1.2m",
                            Language = "vi-VN",
                            Name = "Giường đôi nhỏ"
                        },
                        new
                        {
                            Id = 4,
                            Description = "One small double bed 1.5m x 2m",
                            Language = "en-US",
                            Name = "Double Bed"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Một giường đôi lớn 1.6m x 2m",
                            Language = "vi-VN",
                            Name = "Giường đôi lớn"
                        },
                        new
                        {
                            Id = 6,
                            Description = "One big double bed 1.6m x 2m",
                            Language = "en-US",
                            Name = "Queen size Bed"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Một giường đôi lớn 1.8m x 2m",
                            Language = "vi-VN",
                            Name = "Giường cỡ lớn"
                        },
                        new
                        {
                            Id = 8,
                            Description = "One big double bed 1.8m x 2m",
                            Language = "en-US",
                            Name = "King size Bed"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Một giường đôi lớn 1.8m x 2.1m",
                            Language = "vi-VN",
                            Name = "Western King Bed"
                        },
                        new
                        {
                            Id = 10,
                            Description = "One big double bed 1.8m x 2.1m",
                            Language = "en-US",
                            Name = "Western King Bed"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Một giường đôi lớn 2m x 2.2m",
                            Language = "vi-VN",
                            Name = "Giường siêu lớn"
                        },
                        new
                        {
                            Id = 12,
                            Description = "One big double bed 2m x 2.2m",
                            Language = "en-US",
                            Name = "Super King size"
                        });
                });

            modelBuilder.Entity("Booking_Backend.Data.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CheckIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 3, 15, 6, 7, 51, 248, DateTimeKind.Utc).AddTicks(6854));

                    b.Property<DateTime>("CheckOut")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 3, 15, 6, 7, 51, 248, DateTimeKind.Utc).AddTicks(6994));

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 3, 15, 6, 7, 51, 248, DateTimeKind.Utc).AddTicks(6560));

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("TotalAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<Guid>("User_Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("User_Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Booking_Backend.Data.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 3, 15, 6, 7, 51, 260, DateTimeKind.Utc).AddTicks(5128));

                    b.Property<int>("Hotel_Id")
                        .HasColumnType("int");

                    b.Property<Guid>("User_Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Hotel_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Booking_Backend.Data.Entities.Extension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExtensionType_Id")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ExtensionType_Id");

                    b.ToTable("Extensions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExtensionType_Id = 1,
                            Language = "vi-VN",
                            Name = "Giấy vệ sinh"
                        },
                        new
                        {
                            Id = 2,
                            ExtensionType_Id = 2,
                            Language = "en-US",
                            Name = "Toilet paper"
                        },
                        new
                        {
                            Id = 3,
                            ExtensionType_Id = 1,
                            Language = "vi-VN",
                            Name = "Khăn tắm"
                        },
                        new
                        {
                            Id = 4,
                            ExtensionType_Id = 2,
                            Language = "en-US",
                            Name = "Bath towel"
                        },
                        new
                        {
                            Id = 5,
                            ExtensionType_Id = 1,
                            Language = "vi-VN",
                            Name = "Chậu rửa vệ sinh (bidet)"
                        },
                        new
                        {
                            Id = 6,
                            ExtensionType_Id = 2,
                            Language = "en-US",
                            Name = "Bidet"
                        },
                        new
                        {
                            Id = 7,
                            ExtensionType_Id = 3,
                            Language = "vi-VN",
                            Name = "Ra trải giường"
                        },
                        new
                        {
                            Id = 8,
                            ExtensionType_Id = 4,
                            Language = "en-US",
                            Name = "Bedspread"
                        },
                        new
                        {
                            Id = 9,
                            ExtensionType_Id = 3,
                            Language = "vi-VN",
                            Name = "Tủ hoặc phòng để quần áo"
                        },
                        new
                        {
                            Id = 10,
                            ExtensionType_Id = 4,
                            Language = "en-US",
                            Name = "Wardrobe or Closet"
                        },
                        new
                        {
                            Id = 11,
                            ExtensionType_Id = 3,
                            Language = "vi-VN",
                            Name = "Đồng hồ báo thức"
                        },
                        new
                        {
                            Id = 12,
                            ExtensionType_Id = 4,
                            Language = "en-US",
                            Name = "Alarm clock"
                        },
                        new
                        {
                            Id = 13,
                            ExtensionType_Id = 5,
                            Language = "vi-VN",
                            Name = "Bàn ăn"
                        },
                        new
                        {
                            Id = 14,
                            ExtensionType_Id = 6,
                            Language = "en-US",
                            Name = "Dining table"
                        },
                        new
                        {
                            Id = 15,
                            ExtensionType_Id = 5,
                            Language = "vi-VN",
                            Name = "Sản phẩm lau rửa"
                        },
                        new
                        {
                            Id = 16,
                            ExtensionType_Id = 6,
                            Language = "en-US",
                            Name = "Cleaning products"
                        },
                        new
                        {
                            Id = 17,
                            ExtensionType_Id = 5,
                            Language = "vi-VN",
                            Name = "Bếp nấu"
                        },
                        new
                        {
                            Id = 18,
                            ExtensionType_Id = 6,
                            Language = "en-US",
                            Name = "Cooking stove"
                        },
                        new
                        {
                            Id = 19,
                            ExtensionType_Id = 7,
                            Language = "vi-VN",
                            Name = "Ổ điện gần giường"
                        },
                        new
                        {
                            Id = 20,
                            ExtensionType_Id = 8,
                            Language = "en-US",
                            Name = "Power outlet near bed"
                        },
                        new
                        {
                            Id = 21,
                            ExtensionType_Id = 9,
                            Language = "vi-VN",
                            Name = "Bàn ghế ngoài trời"
                        },
                        new
                        {
                            Id = 22,
                            ExtensionType_Id = 10,
                            Language = "en-US",
                            Name = "Outdoor furniture"
                        },
                        new
                        {
                            Id = 23,
                            ExtensionType_Id = 9,
                            Language = "vi-VN",
                            Name = "Sân hiên phơi nắng"
                        },
                        new
                        {
                            Id = 24,
                            ExtensionType_Id = 10,
                            Language = "en-US",
                            Name = "Sun deck"
                        },
                        new
                        {
                            Id = 25,
                            ExtensionType_Id = 9,
                            Language = "vi-VN",
                            Name = "Tiện nghi BBQ"
                        },
                        new
                        {
                            Id = 26,
                            ExtensionType_Id = 10,
                            Language = "en-US",
                            Name = "BBQ facilities"
                        });
                });

            modelBuilder.Entity("Booking_Backend.Data.Entities.ExtensionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Language")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("ExtensionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Language = "vi-VN",
                            Name = "Phòng tắm"
                        },
                        new
                        {
                            Id = 2,
                            Language = "en-US",
                            Name = "Bathroom"
                        },
                        new
                        {
                            Id = 3,
                            Language = "vi-VN",
                            Name = "Phòng ngủ"
                        },
                        new
                        {
                            Id = 4,
                            Language = "en-US",
                            Name = "Bedroom"
                        },
                        new
                        {
                            Id = 5,
                            Language = "vi-VN",
                            Name = "Nhà bếp"
                        },
                        new
                        {
                            Id = 6,
                            Language = "en-US",
                            Name = "Kitchen"
                        },
                        new
                        {
                            Id = 7,
                            Language = "vi-VN",
                            Name = "Tiện ích trong phòng"
                        },
                        new
                        {
                            Id = 8,
                            Language = "en-US",
                            Name = "In-room amenities"
                        },
                        new
                        {
                            Id = 9,
                            Language = "vi-VN",
                            Name = "Ngoài trời"
                        },
                        new
                        {
                            Id = 10,
                            Language = "en-US",
                            Name = "Outdoor"
                        },
                        new
                        {
                            Id = 11,
                            Language = "vi-VN",
                            Name = "Chăm sóc sức khỏe"
                        },
                        new
                        {
                            Id = 12,
                            Language = "en-US",
                            Name = "Healthcare"
                        },
                        new
                        {
                            Id = 13,
                            Language = "vi-VN",
                            Name = "Lối vào dành cho người khuyết tật"
                        },
                        new
                        {
                            Id = 14,
                            Language = "en-US",
                            Name = "Disabled access"
                        },
                        new
                        {
                            Id = 15,
                            Language = "vi-VN",
                            Name = "Tổng quát"
                        },
                        new
                        {
                            Id = 16,
                            Language = "en-US",
                            Name = "General"
                        },
                        new
                        {
                            Id = 17,
                            Language = "vi-VN",
                            Name = "An ninh"
                        },
                        new
                        {
                            Id = 18,
                            Language = "en-US",
                            Name = "Security"
                        },
                        new
                        {
                            Id = 19,
                            Language = "vi-VN",
                            Name = "Chỗ đậu xe"
                        },
                        new
                        {
                            Id = 20,
                            Language = "en-US",
                            Name = "Parking"
                        },
                        new
                        {
                            Id = 21,
                            Language = "vi-VN",
                            Name = "Internet"
                        },
                        new
                        {
                            Id = 28,
                            Language = "en-US",
                            Name = "Internet"
                        },
                        new
                        {
                            Id = 22,
                            Language = "vi-VN",
                            Name = "Đồ ăn & thức uống"
                        },
                        new
                        {
                            Id = 23,
                            Language = "en-US",
                            Name = "Food & Beverage"
                        },
                        new
                        {
                            Id = 24,
                            Language = "vi-VN",
                            Name = "Truyền thông & Công nghệ"
                        },
                        new
                        {
                            Id = 25,
                            Language = "en-US",
                            Name = "Media & Technology"
                        },
                        new
                        {
                            Id = 26,
                            Language = "vi-VN",
                            Name = "Khu vực phòng khách"
                        },
                        new
                        {
                            Id = 27,
                            Language = "en-US",
                            Name = "Living Room Area"
                        });
                });

            modelBuilder.Entity("Booking_Backend.Data.Entities.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Establish")
                        .HasColumnType("date");

                    b.Property<int>("HotelType_Id")
                        .HasColumnType("int");

                    b.Property<string>("Hotline")
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Language")
                        .HasColumnType("varchar(5)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ViewHotel_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HotelType_Id");

                    b.HasIndex("ViewHotel_Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "12 đường Bà Triệu, Đà Lạt",
                            Area = "Đà Lạt",
                            Establish = new DateTime(2002, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelType_Id = 1,
                            Hotline = "02963678333",
                            Language = "vi-VN",
                            Latitude = 0m,
                            Longitude = 0m,
                            Name = "Khách sạn Lê Tuấn Minh",
                            Thumbnail = "/images/Thumnails/508886577.jpg",
                            ViewHotel_Id = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "12 Ba Trieu Street, Da Lat",
                            Area = "Da Lat",
                            Establish = new DateTime(2002, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelType_Id = 2,
                            Hotline = "02963678333",
                            Language = "en-US",
                            Latitude = 0m,
                            Longitude = 0m,
                            Name = "Le Minh Tuan Hotel",
                            Thumbnail = "/images/Thumnails/508886577.jpg",
                            ViewHotel_Id = 2
                        });
                });

            modelBuilder.Entity("Booking_Backend.Data.Entities.HotelType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageUrl")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Language")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("HotelTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "/images/HotelTypes/khachsan.jpg",
                            Language = "vi-VN",
                            Name = "Khách sạn"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "/images/HotelTypes/khachsan.jpg",
                            Language = "en-US",
                            Name = "Hotel"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "/images/HotelTypes/nhanghi.jpg",
                            Language = "vi-VN",
                            Name = "Nhà nghỉ"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "/images/HotelTypes/nhanghi.jpg",
                            Language = "en-US",
                            Name = "Lodging"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "/images/HotelTypes/homestay.jpg",
                            Language = "vi-VN",
                            Name = "Homestay"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "/images/HotelTypes/homestay.jpg",
                            Language = "en-US",
                            Name = "Homestay"
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "/images/HotelTypes/canho.jpg",
                            Language = "vi-VN",
                            Name = "Căn hộ"
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "/images/HotelTypes/canho.jpg",
                            Language = "en-US",
                            Name = "Apartment"
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "/images/HotelTypes/bietthu.jpg",
                            Language = "vi-VN",
                            Name = "Biệt thự"
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "/images/HotelTypes/bietthu.jpg",
                            Language = "en-US",
                            Name = "Villa"
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "/images/HotelTypes/resort.jpg",
                            Language = "vi-VN",
                            Name = "Khu nghỉ dưỡng"
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "/images/HotelTypes/resort.jpg",
                            Language = "en-US",
                            Name = "Resort"
                        },
                        new
                        {
                            Id = 13,
                            ImageUrl = "/images/HotelTypes/cannha.jpg",
                            Language = "vi-VN",
                            Name = "Nhà nguyên căn"
                        },
                        new
                        {
                            Id = 14,
                            ImageUrl = "/images/HotelTypes/cannha.jpg",
                            Language = "en-US",
                            Name = "House"
                        });
                });

            modelBuilder.Entity("Booking_Backend.Data.Entities.HotelTypeImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 3, 15, 6, 7, 51, 304, DateTimeKind.Utc).AddTicks(4278));

                    b.Property<int>("HotelType_Id")
                        .HasColumnType("int");

                    b.Property<decimal>("ImageSize")
                        .HasColumnType("decimal");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("isDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("HotelType_Id");

                    b.ToTable("HotelTypeImages");
                });

            modelBuilder.Entity("Booking_Backend.Data.Entities.Hotel_Service", b =>
                {
                    b.Property<int>("Hotel_Id")
                        .HasColumnType("int");

                    b.Property<int>("Service_Id")
                        .HasColumnType("int");

                    b.Property<bool>("Surcharge")
                        .HasColumnType("bit");

                    b.HasKey("Hotel_Id", "Service_Id");

                    b.HasIndex("Service_Id");

                    b.ToTable("Hotel_Services");
                });

            modelBuilder.Entity("Booking_Backend.Data.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 3, 15, 6, 7, 51, 290, DateTimeKind.Utc).AddTicks(7758));

                    b.Property<int>("Hotel_Id")
                        .HasColumnType("int");

                    b.Property<decimal>("ImageSize")
                        .HasColumnType("decimal");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Hotel_Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Booking_Backend.Data.Entities.Language", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(5)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = "vi-VN",
                            IsDefault = true,
                            Name = "Tiếng Việt"
                        },
                        new
                        {
                            Id = "en-US",
                            IsDefault = false,
                            Name = "English"
                        });
                });

            modelBuilder.Entity("Booking_Backend.Data.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Bed_Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hotel_Id")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .HasColumnType("varchar(5)");

                    b.Property<int>("Maximum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal>("PriceByHour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("PriceOverNight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("RoomCode")
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoomType_Id")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Bed_Id");

                    b.HasIndex("Hotel_Id");

                    b.HasIndex("RoomType_Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Booking_Backend.Data.Entities.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Language")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Language = "vi-VN",
                            Name = "Phòng Standard"
                        },
                        new
                        {
                            Id = 2,
                            Language = "en-US",
                            Name = "Standard Room"
                        },
                        new
                        {
                            Id = 3,
                            Language = "vi-VN",
                            Name = "Phòng Superior"
                        },
                        new
                        {
                            Id = 4,
                            Language = "en-US",
                            Name = "Superior Room"
                        },
                        new
                        {
                            Id = 5,
                            Language = "vi-VN",
                            Name = "Phòng Deluxe"
                        },
                        new
                        {
                            Id = 6,
                            Language = "en-US",
                            Name = "Deluxe Room"
                        },
                        new
                        {
                            Id = 7,
                            Language = "vi-VN",
                            Name = "Phòng Suite"
                        },
                        new
                        {
                            Id = 8,
                            Language = "en-US",
                            Name = "Suite Room"
                        },
                        new
                        {
                            Id = 9,
                            Language = "vi-VN",
                            Name = "Phòng Junior Suit"
                        },
                        new
                        {
                            Id = 10,
                            Language = "en-US",
                            Name = "Junior Suite Room"
                        },
                        new
                        {
                            Id = 11,
                            Language = "vi-VN",
                            Name = "Phòng Executive Suite"
                        },
                        new
                        {
                            Id = 12,
                            Language = "en-US",
                            Name = "Executive Suite Room"
                        });
                });

            modelBuilder.Entity("Booking_Backend.Data.Entities.Room_Booking", b =>
                {
                    b.Property<int>("Room_Id")
                        .HasColumnType("int");

                    b.Property<int>("Booking_Id")
                        .HasColumnType("int");

                    b.HasKey("Room_Id", "Booking_Id");

                    b.HasIndex("Booking_Id");

                    b.ToTable("Room_Bookings");
                });

            modelBuilder.Entity("Booking_Backend.Data.Entities.Room_Extension", b =>
                {
                    b.Property<int>("Room_Id")
                        .HasColumnType("int");

                    b.Property<int>("Extension_Id")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Room_Id", "Extension_Id");

                    b.HasIndex("Extension_Id");

                    b.ToTable("Room_Extensions");
                });

            modelBuilder.Entity("Booking_Backend.Data.Entities.ServiceHotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Booking_Backend.Data.Entities.UserImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 3, 15, 6, 7, 51, 302, DateTimeKind.Utc).AddTicks(6578));

                    b.Property<decimal>("ImageSize")
                        .HasColumnType("decimal");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("User_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("User_Id");

                    b.ToTable("UserImages");
                });

            modelBuilder.Entity("Booking_Backend.Data.Entities.ViewHotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Language")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("ViewHotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "/images/ViewHotels/viewtrungtam.jpg",
                            Language = "vi-VN",
                            Name = "Trung tâm thành phố"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "/images/ViewHotels/viewtrungtam.jpg",
                            Language = "en-US",
                            Name = "City center"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("AppUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("b5e9ebbd-fd85-4ad0-b820-0aa8105ebdd2"),
                            RoleId = new Guid("265e11da-bc22-4fe7-b286-493d6a09d46f")
                        },
                        new
                        {
                            UserId = new Guid("31ff741e-5a2a-4afd-8448-7dc59c03a5b6"),
                            RoleId = new Guid("1f10d63e-c240-4be5-a95b-b868c41501dd")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserTokens");
                });

            modelBuilder.Entity("Booking_Backend.Data.Entities.Booking", b =>
                {
                    b.HasOne("Booking_Backend.Data.Entities.AppUser", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Booking_Backend.Data.Entities.Comment", b =>
                {
                    b.HasOne("Booking_Backend.Data.Entities.Hotel", "Hotel")
                        .WithMany("Comments")
                        .HasForeignKey("Hotel_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booking_Backend.Data.Entities.AppUser", "User")
                        .WithMany("Comments")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Booking_Backend.Data.Entities.Extension", b =>
                {
                    b.HasOne("Booking_Backend.Data.Entities.ExtensionType", "ExtensionType")
                        .WithMany("Extensions")
                        .HasForeignKey("ExtensionType_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Booking_Backend.Data.Entities.Hotel", b =>
                {
                    b.HasOne("Booking_Backend.Data.Entities.HotelType", "HotelType")
                        .WithMany("Hotels")
                        .HasForeignKey("HotelType_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booking_Backend.Data.Entities.ViewHotel", "ViewHotel")
                        .WithMany("Hotels")
                        .HasForeignKey("ViewHotel_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Booking_Backend.Data.Entities.HotelTypeImage", b =>
                {
                    b.HasOne("Booking_Backend.Data.Entities.HotelType", "HotelType")
                        .WithMany("HotelTypeImages")
                        .HasForeignKey("HotelType_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Booking_Backend.Data.Entities.Hotel_Service", b =>
                {
                    b.HasOne("Booking_Backend.Data.Entities.Hotel", "Hotel")
                        .WithMany("Hotel_Services")
                        .HasForeignKey("Hotel_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booking_Backend.Data.Entities.ServiceHotel", "Service")
                        .WithMany("Hotel_Services")
                        .HasForeignKey("Service_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Booking_Backend.Data.Entities.Image", b =>
                {
                    b.HasOne("Booking_Backend.Data.Entities.Hotel", "Hotel")
                        .WithMany("Images")
                        .HasForeignKey("Hotel_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Booking_Backend.Data.Entities.Room", b =>
                {
                    b.HasOne("Booking_Backend.Data.Entities.Bed", "Bed")
                        .WithMany("Rooms")
                        .HasForeignKey("Bed_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booking_Backend.Data.Entities.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("Hotel_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booking_Backend.Data.Entities.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomType_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Booking_Backend.Data.Entities.Room_Booking", b =>
                {
                    b.HasOne("Booking_Backend.Data.Entities.Booking", "Booking")
                        .WithMany("Room_Bookings")
                        .HasForeignKey("Booking_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booking_Backend.Data.Entities.Room", "Room")
                        .WithMany("Room_Bookings")
                        .HasForeignKey("Room_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Booking_Backend.Data.Entities.Room_Extension", b =>
                {
                    b.HasOne("Booking_Backend.Data.Entities.Extension", "Extension")
                        .WithMany("Room_Extensions")
                        .HasForeignKey("Extension_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booking_Backend.Data.Entities.Room", "Room")
                        .WithMany("Room_Extensions")
                        .HasForeignKey("Room_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Booking_Backend.Data.Entities.UserImage", b =>
                {
                    b.HasOne("Booking_Backend.Data.Entities.AppUser", "User")
                        .WithMany("UserImages")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
